name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@1.0.9
    - run: docker build -f Containerfile -t discard2-test --target test .
    - run: docker run discard2-test
